# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://ivandalmet.netlify.com/*"
  to = "https://ivan.dalmet.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.ivan.dalmet.fr/*"
  to = "https://ivan.dalmet.fr/:splat"
  status = 301
  force = true

